apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf

    [INPUT]
        Name              tail
        Path              /shared-logs/*.log
        Parser            springboot
        Tag               shared.*
        Refresh_Interval  5
        Rotate_Wait       30
        Mem_Buf_Limit     50MB
        Skip_Long_Lines   On
        DB                /fluent-bit/tail-db/tail-shared.db

    [OUTPUT]
        Name          loki
        Match         *
        Host          host.docker.internal
        Port          32100
        Labels        job=fluent-bit,source=shared,app=$filename
        Line_Format   json
        Retry_Limit   False

  parsers.conf: |
    [PARSER]
        Name        springboot
        Format      regex
        Regex       ^(?<time>[^ ]+ [^ ]+)\s+\[[^\]]+\] (?<level>[A-Z]+)\s+(?<logger>[^ ]+) - (?<msg>.*)$
        Time_Key    time
        Time_Format %Y-%m-%d %H:%M:%S.%L
        Time_Keep   On

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  labels:
    app: fluent-bit
spec:
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      containers:
        - name: fluent-bit
          image: fluent/fluent-bit:1.9.9
          volumeMounts:
            - name: config
              mountPath: /fluent-bit/etc
            - name: tail-db
              mountPath: /fluent-bit/tail-db
            - name: shared-logs
              mountPath: /shared-logs
      volumes:
        - name: config
          configMap:
            name: fluent-bit-config
        - name: tail-db
          emptyDir: {}
        - name: shared-logs
          hostPath:
            path: /shared-logs
            type: DirectoryOrCreate