apiVersion: v1
kind: Service
metadata:
  name: oauth2-service
spec:
  selector:
    app: oauth2-server
  type: NodePort
  ports:
    - protocol: TCP
      port: 8085        # Порт внутри кластера
      targetPort: 8085  # Порт контейнера
      nodePort: 30005   # Порт на хосте (внешний)