apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-server
  template:
    metadata:
      labels:
        app: oauth2-server
    spec:
      containers:
        - name: oauth2-server
          image: quay.io/keycloak/keycloak:latest
          args: ["start-dev", "--import-realm"]
          ports:
            - containerPort: 8085
          env:
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: "admin"
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              value: "password"
            - name: KC_HTTP_PORT
              value: "8085"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_PROXY
              value: "edge"
            - name: KC_HOSTNAME_STRICT
              value: "false"
          volumeMounts:
            - name: realm-source
              mountPath: /opt/keycloak/data/import
      volumes:
        - name: realm-source
          hostPath:
            path: /Users/ilyaivanov/IdeaProjects/APIGateway/keycloack
            type: DirectoryOrCreate