apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s

    scrape_configs:
      - job_name: 'spring-microservices'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets:
              - 'data-collector-service:8081'
              - 'data-processor-service:8081'
              - 'analytics-service:8081'
              - 'notification-service:8081'
              - 'storage-service:8081'
              - 'apigateway-service.default.svc.cluster.local:8081'